### ISSUE TITLE
Explication sur thème

### ISSUE THREAD

**Issue by Michelgard** [arthurlacoste/MastodonCloudTheme#1]
Bonjour,
J'ai installé vos thèmes c'est très pratique d'avoir l'utilisation complète de l'écran sur Mastodon. Merci
Par contre je ne comprends pas ce thème : MastodonCloudThemePicResizer.user.js je ne vois pas de modification
Merci

**Comment by arthurlacoste** [comment]
Bonjour, ce script sert à élargir l'aperçu des images.
